{% set name = "toml-f" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/toml-f/toml-f/releases/download/v0.3.1/toml-f-{{ version }}.tar.xz
  sha256: 7f40f60c8d9ffbb1b99fb051a3e6682c7dd04d7479aa1cf770eff8174b02544f
  patches:
    - no-test-drive.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - toml-test

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --exact-version {{ version }}
    - test -f $PREFIX/lib/lib{{ name }}$SHLIB_EXT  # [unix]
    - test ! -f $PREFIX/lib/lib{{ name }}.a  # [unix]

about:
  home: https://toml-f.readthedocs.io
  dev_url: https://github.com/toml-f/toml-f
  doc_url: https://toml-f.github.io/toml-f
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-Apache
    - LICENSE-MIT
  summary: >-
    TOML parser implementation for data serialization and deserialization in Fortran 

extra:
  recipe-maintainers:
    - awvwgk
